(function initAtestados(){
  "use strict";
  const TABLE="ete_atestados_justified_absences";
  const ROOMS=[
    {group:"DS",label:"Desenvolvimento de Sistemas",rooms:["1º DS A","1º DS B","2º DS A","2º DS B"]},
    {group:"EDF",label:"Edificações",rooms:["1º EDF A","1º EDF B","2º EDF A","2º EDF B","3º EDF A","3º EDF B"]},
    {group:"GTU",label:"GTU",rooms:["3º GTU"]}
  ];
  let root=null,rows=[],activeTab="overview",channel=null;

  function user(){try{return typeof currentUser!=="undefined"?currentUser:null;}catch(_){return null;}}
  function role(){return String(user()?.role||"").toLowerCase();}
  function canManage(){return ["adm","diretor","vice_diretor"].includes(role());}
  function client(){try{return typeof sb!=="undefined"?sb:null;}catch(_){return null;}}
  function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"})[c]);}
  function num(v){const n=Number(v);return Number.isFinite(n)?n:0;}
  function fmtDate(v){if(!v)return"—";return new Date(v+"T12:00:00").toLocaleDateString("pt-BR");}
  function initials(name){return String(name||"?").trim().split(/\s+/).slice(0,2).map(x=>x[0]?.toUpperCase()||"").join("")||"?";}
  function classes(){return [...new Set(rows.map(r=>String(r.class_name||"").trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"pt-BR"));}
  function avg(list){return list.length?list.reduce((s,r)=>s+num(r.justified_rate),0)/list.length:0;}
  function today(){return new Date().toISOString().slice(0,10);}
  function courseOf(cls){const c=String(cls||"").toUpperCase();if(c.includes("EDF"))return"EDF";if(c.includes("GTU"))return"GTU";return"DS";}
  function icon(name){const i={doc:'<svg viewBox="0 0 24 24"><path d="M7 3.5h7l4 4v13H7z"/><path d="M14 3.5v4h4M10 12h5M10 15h5"/></svg>',users:'<svg viewBox="0 0 24 24"><path d="M8 12a3 3 0 1 0 0-6 3 3 0 0 0 0 6ZM16 11a2.5 2.5 0 1 0 0-5M3 19c.3-3 2-4.5 5-4.5s4.7 1.5 5 4.5M14 14.8c2.8.1 4.4 1.5 4.8 4.2"/></svg>',rate:'<svg viewBox="0 0 24 24"><path d="M5 18 18 5M7 8a2 2 0 1 0 0-4 2 2 0 0 0 0 4ZM17 20a2 2 0 1 0 0-4 2 2 0 0 0 0 4Z"/></svg>',today:'<svg viewBox="0 0 24 24"><rect x="4" y="5.5" width="16" height="14" rx="2"/><path d="M8 3.5v4M16 3.5v4M4 9.5h16M8 13h3"/></svg>',search:'<svg viewBox="0 0 24 24"><circle cx="11" cy="11" r="6"/><path d="m16 16 4 4"/></svg>',chart:'<svg viewBox="0 0 24 24"><path d="M5 19V9M12 19V5M19 19v-7"/></svg>',folder:'<svg viewBox="0 0 24 24"><path d="M4 7.5h6l2 2h8v9H4z"/></svg>',info:'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="8"/><path d="M12 10v6M12 7.5h.01"/></svg>'};return i[name]||i.doc;}

  function shell(){return '<section class="ete-atestados">'
    +'<header class="at-page-head"><div class="at-heading"><span class="at-eyebrow">Gestão de frequência</span><h1>Atestados</h1><p>Central de faltas justificadas para gestão e consulta dos professores.</p></div><div class="at-head-actions"><span class="at-status" id="atStatus">Sincronizando...</span>'+(canManage()?'<button class="at-btn primary" type="button" data-at-new><span>+</span> Novo registro</button>':'')+'</div></header>'
    +'<nav class="at-nav" aria-label="Navegação do módulo"><button class="at-nav-item active" data-at-tab="overview" type="button">Visão geral</button><button class="at-nav-item" data-at-tab="records" type="button">Registros</button>'+(canManage()?'<button class="at-nav-item" data-at-tab="new" type="button">Cadastrar</button>':'')+'</nav><div id="atView" class="at-view"></div></section>';}

  function metric(label,value,sub,kind,tone){return '<article class="at-metric '+(tone||'')+'"><span class="at-metric-icon">'+icon(kind)+'</span><div><strong>'+value+'</strong><span>'+label+'</span><small>'+sub+'</small></div></article>';}
  function rowHtml(r){return '<tr><td><div class="at-student-cell"><span class="at-avatar">'+esc(initials(r.student_name))+'</span><div><strong>'+esc(r.student_name)+'</strong><small>'+esc(r.reason)+'</small></div></div></td><td><span class="at-badge">'+esc(r.class_name)+'</span></td><td>'+fmtDate(r.absence_date)+'</td><td>'+esc(r.project_name||"Nenhum")+'</td><td><span class="at-rate">'+num(r.justified_rate).toFixed(1).replace(".",",")+'%</span></td>'+(canManage()?'<td><button class="at-icon-danger" title="Excluir registro" type="button" data-at-delete="'+esc(r.id)+'">×</button></td>':'')+'</tr>';}

  function filterRows(){const q=String(root?.querySelector("#atSearch")?.value||"").trim().toLocaleLowerCase("pt-BR");const cls=String(root?.querySelector("#atClassFilter")?.value||"");const mode=String(root?.querySelector("[data-at-filter].active")?.dataset.atFilter||"all");return rows.filter(r=>{const hay=[r.student_name,r.class_name,r.reason,r.project_name].join(" ").toLocaleLowerCase("pt-BR");const modeOk=mode==="all"||(mode==="today"&&r.absence_date===today())||(mode==="project"&&r.project_name)||(mode==="recent"&&String(r.created_at||"").slice(0,10)>=new Date(Date.now()-7*864e5).toISOString().slice(0,10));return(!q||hay.includes(q))&&(!cls||r.class_name===cls)&&modeOk;});}

  function renderOverview(){
    const total=rows.length,cls=classes(),todayRows=rows.filter(r=>r.absence_date===today()),withProject=rows.filter(r=>r.project_name),overall=avg(rows);
    const recent=[...rows].sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at))).slice(0,5);
    const byClass=cls.map(c=>{const list=rows.filter(r=>r.class_name===c);return{name:c,count:list.length,rate:avg(list)};}).sort((a,b)=>b.count-a.count);
    const byCourse=["DS","EDF","GTU"].map(c=>({name:c,count:rows.filter(r=>courseOf(r.class_name)===c).length}));
    const maxCourse=Math.max(1,...byCourse.map(x=>x.count));
    const topClass=byClass[0];
    root.querySelector("#atView").innerHTML=''
      +'<section class="at-metrics">'+metric("Faltas justificadas",total,"Total registrado","doc","blue")+metric("Turmas ativas",cls.length,"Com pelo menos 1 registro","users","violet")+metric("Taxa média",overall.toFixed(1).replace(".",",")+"%","Média informada","rate","green")+metric("Justificadas hoje",todayRows.length,"Registros da data atual","today","amber")+'</section>'
      +'<section class="at-dashboard-grid"><article class="at-card at-main-records"><div class="at-card-head at-main-head"><div><span class="at-card-kicker">Consulta rápida</span><strong>Faltas justificadas</strong><small>Verifique antes de registrar uma falta não justificada.</small></div><button type="button" data-at-tab="records">Ver todos</button></div><div class="at-overview-toolbar"><div class="at-filter-tabs"><button class="active" type="button" data-at-filter="all">Todos <span>'+total+'</span></button><button type="button" data-at-filter="today">Hoje <span>'+todayRows.length+'</span></button><button type="button" data-at-filter="project">Com projeto <span>'+withProject.length+'</span></button><button type="button" data-at-filter="recent">7 dias</button></div></div><div class="at-inline-search"><label><span>'+icon("search")+'</span><input id="atSearch" class="at-input" type="search" placeholder="Pesquisar aluno, turma, motivo ou projeto"></label><select id="atClassFilter" class="at-select"><option value="">Todas as turmas</option>'+cls.map(c=>'<option value="'+esc(c)+'">'+esc(c)+'</option>').join("")+'</select></div><div id="atTableWrap"></div></article>'
      +'<aside class="at-side-stack"><article class="at-card at-course-card"><div class="at-card-head"><div><span class="at-card-kicker">Distribuição</span><strong>Registros por curso</strong></div><span class="at-head-icon">'+icon("chart")+'</span></div><div class="at-course-list">'+byCourse.map(c=>'<div class="at-course-row"><div><strong>'+c.name+'</strong><small>'+c.count+' registro'+(c.count===1?'':'s')+'</small></div><div class="at-mini-track"><span style="width:'+Math.max(c.count?8:0,c.count/maxCourse*100)+'%"></span></div><b>'+c.count+'</b></div>').join("")+'</div></article>'
      +'<article class="at-card at-highlight"><span class="at-card-kicker">Destaque atual</span><strong>'+(topClass?esc(topClass.name):'Sem dados')+'</strong><p>'+(topClass?topClass.count+' registro'+(topClass.count===1?'':'s')+' · taxa média de '+topClass.rate.toFixed(1).replace(".",",")+'%':'A turma com mais registros aparecerá aqui.')+'</p><button type="button" data-at-tab="records">Abrir registros</button></article></aside></section>'
      +'<section class="at-bottom-grid"><article class="at-card at-recent-panel"><div class="at-card-head"><div><span class="at-card-kicker">Atividade</span><strong>Registros recentes</strong></div><button type="button" data-at-tab="records">Ver todos</button></div><div class="at-recent">'+(recent.length?recent.map(r=>'<div class="at-recent-row"><span class="at-avatar">'+esc(initials(r.student_name))+'</span><div><strong>'+esc(r.student_name)+'</strong><small>'+esc(r.class_name)+' · '+fmtDate(r.absence_date)+'</small></div><span class="at-rate">'+num(r.justified_rate).toFixed(1).replace(".",",")+'%</span></div>').join(""):'<div class="at-empty-state compact"><strong>Nenhum registro recente</strong><span>A atividade aparecerá aqui.</span></div>')+'</div></article>'
      +'<article class="at-card at-guide-panel"><div class="at-card-head"><div><span class="at-card-kicker">Fluxo recomendado</span><strong>Antes de marcar falta</strong></div><span class="at-head-icon">'+icon("info")+'</span></div><div class="at-guide-list"><p><span>1</span>Pesquise o nome do aluno.</p><p><span>2</span>Confira turma, data e motivo.</p><p><span>3</span>Considere a ausência como justificada quando houver registro correspondente.</p><p><span>4</span>Em caso de dúvida, confirme com a gestão.</p></div></article></section>';
    root.querySelectorAll("[data-at-filter]").forEach(b=>b.addEventListener("click",()=>{root.querySelectorAll("[data-at-filter]").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderOverviewTable();}));
    root.querySelector("#atSearch")?.addEventListener("input",renderOverviewTable);root.querySelector("#atClassFilter")?.addEventListener("change",renderOverviewTable);renderOverviewTable();
  }

  function renderOverviewTable(){const wrap=root.querySelector("#atTableWrap");if(!wrap)return;const list=filterRows().slice(0,6);wrap.innerHTML=list.length?'<div class="at-table-wrap"><table class="at-table"><thead><tr><th>Aluno</th><th>Turma</th><th>Data</th><th>Projeto</th><th>Taxa</th>'+(canManage()?'<th></th>':'')+'</tr></thead><tbody>'+list.map(rowHtml).join("")+'</tbody></table></div>':'<div class="at-empty-state"><strong>Nenhum registro encontrado</strong><span>Ajuste os filtros ou cadastre uma falta justificada.</span>'+(canManage()?'<button class="at-btn primary" type="button" data-at-new>+ Novo registro</button>':'')+'</div>';}

  function renderRecords(){const opts=classes().map(c=>'<option value="'+esc(c)+'">'+esc(c)+'</option>').join("");root.querySelector("#atView").innerHTML='<section class="at-card at-records-card"><div class="at-records-top"><div><span class="at-card-kicker">Consulta completa</span><h2>Todos os registros</h2><p>Pesquise faltas justificadas por aluno, turma, motivo ou projeto.</p></div>'+(canManage()?'<button class="at-btn primary" type="button" data-at-new>+ Novo registro</button>':'')+'</div><div class="at-records-summary"><span><b>'+rows.length+'</b> registros</span><span><b>'+classes().length+'</b> turmas</span><span><b>'+rows.filter(r=>r.project_name).length+'</b> com projeto</span></div><div class="at-toolbar"><label class="at-search-wrap"><span>'+icon("search")+'</span><input id="atSearch" class="at-input" type="search" placeholder="Buscar aluno, motivo ou projeto"></label><select id="atClassFilter" class="at-select"><option value="">Todas as turmas</option>'+opts+'</select></div><div id="atTableWrap"></div></section>';root.querySelector("#atSearch")?.addEventListener("input",renderTable);root.querySelector("#atClassFilter")?.addEventListener("change",renderTable);renderTable();}
  function renderTable(){const wrap=root.querySelector("#atTableWrap");if(!wrap)return;const list=filterRows();wrap.innerHTML=list.length?'<div class="at-table-wrap"><table class="at-table"><thead><tr><th>Aluno</th><th>Turma</th><th>Data</th><th>Projeto</th><th>Taxa</th>'+(canManage()?'<th></th>':'')+'</tr></thead><tbody>'+list.map(rowHtml).join("")+'</tbody></table></div>':'<div class="at-empty-state"><strong>Nenhum registro encontrado</strong><span>Ajuste a busca ou o filtro de turma.</span></div>';}

  function roomPicker(){return '<div class="at-room-picker"><label>Turma</label><div class="at-room-groups">'+ROOMS.map(group=>'<section class="at-room-group '+(group.group==="GTU"?'gtu':'')+'"><div class="at-room-group-title"><span>'+esc(group.group)+'</span><small>'+esc(group.label)+'</small></div><div class="at-room-options">'+group.rooms.map(room=>'<label class="at-room-option"><input type="radio" name="atClass" value="'+esc(room)+'" required><span>'+esc(room)+'</span></label>').join("")+'</div></section>').join("")+'</div><span class="at-room-help">Selecione a turma.</span></div>';}
  function renderForm(){if(!canManage()){activeTab="records";render();return;}root.querySelector("#atView").innerHTML='<section class="at-form-layout"><aside class="at-form-intro"><span class="at-card-kicker">Novo registro</span><h2>Cadastrar falta justificada</h2><p>Registre a ausência para que professores tenham a informação antes de lançar uma falta não justificada.</p><div class="at-form-steps"><div><b>1</b><span>Identifique aluno e turma</span></div><div><b>2</b><span>Informe data e motivo</span></div><div><b>3</b><span>Salve para disponibilizar em tempo real</span></div></div><div class="at-form-note"><strong>Visibilidade imediata</strong><span>Após salvar, o registro aparece na visão geral e na consulta completa.</span></div></aside><div class="at-card at-form-card"><form id="atForm" class="at-form"><div class="at-field full"><label>Nome do aluno</label><input class="at-input" id="atStudent" required maxlength="160" placeholder="Nome completo do aluno"></div>'+roomPicker()+'<div class="at-field"><label>Data da falta</label><input class="at-input" id="atDate" type="date" required value="'+today()+'"></div><div class="at-field"><label>Projeto <span>opcional</span></label><input class="at-input" id="atProject" maxlength="160" placeholder="Nenhum ou nome do projeto"></div><div class="at-field full"><label>Motivo da falta</label><textarea class="at-textarea" id="atReason" required maxlength="500" placeholder="Ex.: atestado médico, consulta, acompanhamento..."></textarea></div><div class="at-field"><label>Taxa justificada (%)</label><input class="at-input" id="atRate" type="number" min="0" max="100" step="0.1" required value="0"><span class="at-help">Mais adiante esse valor poderá ser automatizado por turma.</span></div><div class="at-form-actions"><button class="at-btn" type="button" data-at-cancel>Cancelar</button><button class="at-btn primary" type="submit">Salvar falta justificada</button></div></form></div></section>';root.querySelector("#atForm")?.addEventListener("submit",saveRecord);}

  function render(){if(!root)return;root.querySelectorAll(".at-nav-item").forEach(b=>b.classList.toggle("active",b.dataset.atTab===activeTab));if(activeTab==="overview")renderOverview();else if(activeTab==="records")renderRecords();else renderForm();}
  function setStatus(text,error){const s=root?.querySelector("#atStatus");if(!s)return;s.textContent=text;s.classList.toggle("error",!!error);}
  async function load(){const c=client();if(!c){setStatus("Supabase indisponível",true);return;}setStatus("Sincronizando...");const{data,error}=await c.from(TABLE).select("*").order("absence_date",{ascending:false}).order("created_at",{ascending:false});if(error){console.error("Atestados:",error);setStatus("Falha ao carregar",true);return;}rows=data||[];setStatus("Atualizado");render();}
  async function saveRecord(event){event.preventDefault();if(!canManage())return;const c=client();if(!c)return;const selected=root.querySelector('input[name="atClass"]:checked');if(!selected){setStatus("Selecione uma turma",true);return;}const btn=event.currentTarget.querySelector('button[type="submit"]');if(btn){btn.disabled=true;btn.textContent="Salvando...";}const payload={student_name:root.querySelector("#atStudent").value.trim(),class_name:selected.value,reason:root.querySelector("#atReason").value.trim(),project_name:root.querySelector("#atProject").value.trim()||null,absence_date:root.querySelector("#atDate").value,justified_rate:num(root.querySelector("#atRate").value)};const{error}=await c.from(TABLE).insert(payload);if(btn){btn.disabled=false;btn.textContent="Salvar falta justificada";}if(error){console.error("Atestados:",error);setStatus("Não foi possível salvar",true);return;}activeTab="records";await load();}
  async function removeRecord(id){if(!canManage()||!id)return;if(!confirm("Excluir este registro de falta justificada?"))return;const c=client();if(!c)return;const{error}=await c.from(TABLE).delete().eq("id",id);if(error){console.error("Atestados:",error);setStatus("Não foi possível excluir",true);return;}await load();}
  function bind(){root.addEventListener("click",e=>{const tab=e.target.closest("[data-at-tab]");if(tab){activeTab=tab.dataset.atTab;render();return;}if(e.target.closest("[data-at-new]")){activeTab="new";render();return;}if(e.target.closest("[data-at-cancel]")){activeTab="overview";render();return;}const del=e.target.closest("[data-at-delete]");if(del)removeRecord(del.dataset.atDelete);});}
  function subscribe(){const c=client();if(!c?.channel)return;try{if(channel)c.removeChannel(channel);}catch(_){}channel=c.channel("ete-atestados-live").on("postgres_changes",{event:"*",schema:"public",table:TABLE},()=>load()).subscribe();}
  function mount(selector){const target=typeof selector==="string"?document.querySelector(selector):selector;if(!target)return;root=target;root.innerHTML=shell();bind();render();load();subscribe();}
  function unmount(){try{const c=client();if(channel&&c)c.removeChannel(channel);}catch(_){}channel=null;if(root)root.innerHTML="";root=null;rows=[];activeTab="overview";}
  window.ETEAtestados={mount,unmount};
})();
